Models Created
IsaacIsrael/wingx pull request #1
Opened 2019-02-18 20:30 UTC by hmdros

2019-02-18 20:33 UTC, tamschmidt submitted a review, later dismissed
ok

2019-02-18 20:44 UTC, tamschmidt submitted a review, later dismissed
ok

2019-02-19 12:49 UTC, IsaacIsrael commented on test/models/facility_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:49 UTC, IsaacIsrael commented on test/models/feature_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:49 UTC, IsaacIsrael commented on test/models/feature_test.rb
> +
Remover este arquivo

2019-02-19 12:49 UTC, IsaacIsrael commented on test/models/flight_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:50 UTC, IsaacIsrael commented on test/models/image_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:50 UTC, IsaacIsrael commented on test/models/order_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:50 UTC, IsaacIsrael commented on test/models/company_test.rb
> +require 'test_helper'
Remover este arquivo

2019-02-19 12:51 UTC, IsaacIsrael requested changes
Remover arquivos teste

2019-02-19 13:41 UTC, IsaacIsrael approved these changes

2019-02-19 13:43 UTC, merged